### PR TITLE
Feature/1 timetracker component

### PR DESCRIPTION
**Pull request by nlawler1737**
React router created

navbar in working order

icons for side bar added

### CODE REVIEW

**Review by lclemente225 — DISMISSED** [review]
Looks good

**Review by AlissonRoss — APPROVED** [review]
Looking good

**Review by AlissonRoss — APPROVED** [review]
I can see the utils/checkValidPassword.js now
image
Looking good

**Review by lclemente225 — APPROVED** [review]
Looks good

**Comment by AlissonRoss** [comment]
Don't forget to add w-4 to the icons and also to see if you want to keep anything from my LandingNavBar.

**Pull request merged**
