### PR TITLE
Feature/85 timetracker page server integration

### PR DESCRIPTION
**Pull request by nlawler1737**
added server integration with time tracker page
 - add entries
 - remove entries
 - quick edit entries

### CODE REVIEW

**Review by AlissonRoss — APPROVED** [review]
Looking good for now but there are some known bugs which we documented in the slides

**Comment by lclemente225** [comment]
image


There is a bug where the date shown is 1 day before the date that was put in. For example, if I input today's date, then it will output "Yesterday".

**Comment by lclemente225** [comment]
image

Note: Another bug for negative time value. We can fix this later.

**Review by lclemente225 — APPROVED** [review]
Super impressive. It connects to the database and you made it so that you can edit the description and times by clicking on each one on a listed entry. Looks good.

**Comment by lclemente225** [comment]
I just noticed that if you edit the time by clicking an existing entry, then it doesn't update on the database. It could be an issue on my end. Just wanted to put this bug in writing on here.

**Review by gdioso — APPROVED** [review]
Looks good, but there is one bug I noticed. When you create an entry and change the project category and then reload the page, the project category defaults back to whatever the first option was. This can be fixed later though.

**Pull request merged**
