### PR TITLE
Feature/39 create account popup menu

### PR DESCRIPTION
**Pull request by nlawler1737**
- created account popup menu

### CODE REVIEW

**Review by lclemente225 — APPROVED** [review]
Looks good

**Comment by AlissonRoss** [comment]
Upon loading the menu pops up. Is that intentional? I would hide it until the user triggers it onClick
image

**Comment by AlissonRoss** [comment]
Hi,
Might benefit from the following:

- Clicking away from the opened popup menu would trigger it to close. This will become handy when the user is moving away in a mobile device so the dialog does not stay opened.

**Review by AlissonRoss — CHANGES_REQUESTED** [review]
Hi,
Might benefit from the following:

    Clicking away from the opened popup menu would trigger it to close. This will become handy when the user is moving away in a mobile device so the dialog does not stay opened.

**Review by AlissonRoss — APPROVED** [review]

**Review by Sillor — APPROVED** [review]
Awesome!

**Pull request merged**
