### PR TITLE
Feature/73 project page server integration

### PR DESCRIPTION
**Pull request by wyzhaobvt**
Make project page integrate with backend

- Input new project name in create-project-dialog will update the database
- Token will save in cookies (The token that I used is the one generated during account creation. Maybe after login page backend integration finishes, the token will be retrieved from login page rather than create-account-page.)
- Project list in project-page will retrieve project data from the database
- If input duplicated project name, it will pop up error message in dialog

To test it:
1. Need to work with PR in timewise-server  Feature/24 Make change on query in loadProjects API
2. Have three tables users, entries, and projects set up in the database

### CODE REVIEW

**Review by AlissonRoss — APPROVED** [review]
Beautiful work

**Comment by AlissonRoss** [comment]
There's a merge conflict that needs resolved:  

1. src/timetracker/pages/create-project-page/CreateProjectDialog.jsx
2. src/timetracker/pages/create-project-page/CreateProjectPage.jsx

**Comment by wyzhaobvt** [comment]
> There's a merge conflict that needs resolved:
> 
> 1. src/timetracker/pages/create-project-page/CreateProjectDialog.jsx
> 2. src/timetracker/pages/create-project-page/CreateProjectPage.jsx

**Comment by wyzhaobvt** [comment]
> There's a merge conflict that needs resolved:
> 
> 1. src/timetracker/pages/create-project-page/CreateProjectDialog.jsx
> 2. src/timetracker/pages/create-project-page/CreateProjectPage.jsx

Conflict resolved. Please check, Thanks!

**Review by AlissonRoss — DISMISSED** [review]

**Pull request closed without merging**
